blank_issues_enabled: true
contact_links:
  - name: Email membership@kctrailclub.org
    url: mailto:membership@kctrailclub.org
    about: Members should email this address with questions or requests
